#!/usr/bin/env python
# -*- coding: utf-8 -*-

from inmetpy.inmet_stations import InmetStation

s = InmetStation()

import sys

args = sys.argv[1:]

if args[0] == 'list_stations':
    s.list_stations(station_type=args[1], save_file=True)

elif args[0] == 'get_all_stations':
    s.get_all_stations(date=args[1], save_file=True)

elif args[0] == 'get_data_station':
    station_id = args[3].strip('[]').replace(" ", "").split(',')
    if len(station_id) == 1:
        station_id = station_id[0]
    s.get_data_station(start_date=args[1], end_date=args[2], station_id=station_id, save_file=True)

else:
    print("Wrong argument")
